branchName: short
autoCloseIssue: true
commentMessage: "Branch ${branchName} created for issue: ${issue.title}"
openPR: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
branches:
  - label: feat
    prefix: feat/
  - label: update
    prefix: update/
  - label: fix
    prefix: fix/
  - label: docs
    prefix: docs/
  - label: style
    prefix: style/
  - label: design
    prefix: design/
  - label: refactor
    prefix: refactor/
  - label: test
    prefix: test/
  - label: chore
    prefix: chore/
